name: Publish

on:
    push:
        tags:
            - 'v*'

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - uses: actions/checkout@v5
            - uses: oven-sh/setup-bun@v2
            - run: bun install --frozen-lockfile
            - name: Publish to GitHub Packages
              run: bun publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}