name: Publish

on:
    push:
        tags:
            - 'v*'

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - uses: actions/checkout@v5
            - uses: oven-sh/setup-bun@v2
            - run: bun install --frozen-lockfile
            - name: Setup registry auth
              run: |
                  echo "@duckflixapp:registry=https://npm.pkg.github.com" >> ~/.npmrc
                  echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}